# Generated by Django 5.0.6 on 2026-09-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_optional_ghanacard'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenuser',
            name='service_department',
            field=models.CharField(blank=True, choices=[('Identity & Personal Documents', 'Identity & Personal Documents'), ("Transport & Driver's Services (DVLA)", "Transport & Driver's Services (DVLA)"), ('Taxes & Payments', 'Taxes & Payments'), ('Health & Insurance', 'Health & Insurance'), ('Social Security', 'Social Security'), ('Business & Company Services', 'Business & Company Services'), ('Safety & Justice', 'Safety & Justice'), ('Utilities & Assembly', 'Utilities & Assembly')], max_length=100),
        ),
    ]
