# Generated by Django 5.0.6 on 2026-08-30 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenApplication',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=200)),
                ('service_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('ready', 'Ready')], default='draft', max_length=20)),
                ('date', models.CharField(max_length=40)),
                ('ref_no', models.CharField(max_length=80)),
                ('form_data', models.JSONField(default=dict)),
                ('documents', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
