# Generated by Django 5.0.6 on 2026-09-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_applicationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenapplication',
            name='service_department',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
