import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:ghanaserve/theme/app_theme.dart';
import 'package:ghanaserve/widgets/app_back_button.dart';

class AboutScreen extends StatelessWidget { const AboutScreen({super.key}); @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(leading: const AppBackButton(), title: const Text('About E-citizen GH')), body: ListView(padding: const EdgeInsets.fromLTRB(20, 12, 20, 32), children: [
  Container(padding: const EdgeInsets.all(24), decoration: BoxDecoration(color: AppColors.ghGreen, borderRadius: BorderRadius.circular(22)), child: Column(children: [const Icon(Icons.public_rounded, color: AppColors.ghGold, size: 48), const SizedBox(height: 12), Text('E-citizen GH', style: GoogleFonts.plusJakartaSans(color: Colors.white, fontSize: 24, fontWeight: FontWeight.w800)), const SizedBox(height: 6), const Text('One app. Many public services.', style: TextStyle(color: Colors.white70))])),
  const SizedBox(height: 24), Text('Making services simpler', style: Theme.of(context).textTheme.displaySmall), const SizedBox(height: 10), const Text('E-citizen GH brings essential government services together in one trusted place. Discover services, submit forms, track applications, make payments and keep your documents close at hand.'), const SizedBox(height: 22),
  const Card(child: Column(children: [ListTile(leading: Icon(Icons.apps_outlined, color: AppColors.ghGreen), title: Text('Services we provide'), subtitle: Text('Identity, passports, licences, health, education, transport and utility services.')), ListTile(leading: Icon(Icons.calendar_today_outlined, color: AppColors.ghGreen), title: Text('Created in 2026'), subtitle: Text('Built to make everyday public services more accessible to everyone in Ghana.')), ListTile(leading: Icon(Icons.verified_outlined, color: AppColors.ghGreen), title: Text('Version 2.1.0'), subtitle: Text('Secure, citizen-first and continually improving.'))])), const SizedBox(height: 24), Center(child: Text('© 2026 E-citizen GH. All rights reserved.', style: Theme.of(context).textTheme.bodySmall))
 ])); }

class PrivacyPolicyScreen extends StatelessWidget { const PrivacyPolicyScreen({super.key}); @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(leading: const AppBackButton(), title: const Text('Privacy Policy')), body: ListView(padding: const EdgeInsets.fromLTRB(20, 10, 20, 32), children: [Text('Your privacy matters', style: Theme.of(context).textTheme.displaySmall), const SizedBox(height: 8), const Text('Last updated: 3 September 2026'), const SizedBox(height: 20), const _Policy(title: 'Information we collect', body: 'We collect the information needed to create your account, verify your identity, process applications and provide support. This may include your name, contact details, Ghana Card information and documents you choose to submit.'), const _Policy(title: 'How we use information', body: 'We use your information to deliver requested public services, communicate application updates, process payments and keep the platform secure. We do not sell your personal information.'), const _Policy(title: 'Your choices', body: 'You can review and update your profile information in the app. You may contact support to ask questions about your data or request help with your account.'), const _Policy(title: 'Security and retention', body: 'We use appropriate safeguards and retain information only for as long as needed to provide services, meet legal obligations and resolve disputes.'), const _Policy(title: 'Contact', body: 'For privacy questions, contact support through the E-citizen GH app or call 0800 100 900.') ])); }
class _Policy extends StatelessWidget { final String title; final String body; const _Policy({required this.title, required this.body}); @override Widget build(BuildContext context) => Padding(padding: const EdgeInsets.only(bottom: 20), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(title, style: Theme.of(context).textTheme.titleLarge), const SizedBox(height: 6), Text(body, style: Theme.of(context).textTheme.bodyMedium)])); }
